// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/blackhatbrigade/gomessagestore/repository (interfaces: Repository)

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	context "context"
	message "github.com/blackhatbrigade/gomessagestore/message"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindAllMessagesInCategory mocks base method
func (m *MockRepository) FindAllMessagesInCategory(arg0 context.Context, arg1 string) ([]*message.MessageEnvelope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllMessagesInCategory", arg0, arg1)
	ret0, _ := ret[0].([]*message.MessageEnvelope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllMessagesInCategory indicates an expected call of FindAllMessagesInCategory
func (mr *MockRepositoryMockRecorder) FindAllMessagesInCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllMessagesInCategory", reflect.TypeOf((*MockRepository)(nil).FindAllMessagesInCategory), arg0, arg1)
}

// FindAllMessagesInCategorySince mocks base method
func (m *MockRepository) FindAllMessagesInCategorySince(arg0 context.Context, arg1 string, arg2 int64) ([]*message.MessageEnvelope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllMessagesInCategorySince", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*message.MessageEnvelope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllMessagesInCategorySince indicates an expected call of FindAllMessagesInCategorySince
func (mr *MockRepositoryMockRecorder) FindAllMessagesInCategorySince(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllMessagesInCategorySince", reflect.TypeOf((*MockRepository)(nil).FindAllMessagesInCategorySince), arg0, arg1, arg2)
}

// FindAllMessagesInStream mocks base method
func (m *MockRepository) FindAllMessagesInStream(arg0 context.Context, arg1 string) ([]*message.MessageEnvelope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllMessagesInStream", arg0, arg1)
	ret0, _ := ret[0].([]*message.MessageEnvelope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllMessagesInStream indicates an expected call of FindAllMessagesInStream
func (mr *MockRepositoryMockRecorder) FindAllMessagesInStream(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllMessagesInStream", reflect.TypeOf((*MockRepository)(nil).FindAllMessagesInStream), arg0, arg1)
}

// FindAllMessagesInStreamSince mocks base method
func (m *MockRepository) FindAllMessagesInStreamSince(arg0 context.Context, arg1 string, arg2 int64) ([]*message.MessageEnvelope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllMessagesInStreamSince", arg0, arg1, arg2)
	ret0, _ := ret[0].([]*message.MessageEnvelope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllMessagesInStreamSince indicates an expected call of FindAllMessagesInStreamSince
func (mr *MockRepositoryMockRecorder) FindAllMessagesInStreamSince(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllMessagesInStreamSince", reflect.TypeOf((*MockRepository)(nil).FindAllMessagesInStreamSince), arg0, arg1, arg2)
}

// FindLastMessageInStream mocks base method
func (m *MockRepository) FindLastMessageInStream(arg0 context.Context, arg1 string) (*message.MessageEnvelope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLastMessageInStream", arg0, arg1)
	ret0, _ := ret[0].(*message.MessageEnvelope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLastMessageInStream indicates an expected call of FindLastMessageInStream
func (mr *MockRepositoryMockRecorder) FindLastMessageInStream(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLastMessageInStream", reflect.TypeOf((*MockRepository)(nil).FindLastMessageInStream), arg0, arg1)
}

// WriteMessage mocks base method
func (m *MockRepository) WriteMessage(arg0 context.Context, arg1 *message.MessageEnvelope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteMessage", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMessage indicates an expected call of WriteMessage
func (mr *MockRepositoryMockRecorder) WriteMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMessage", reflect.TypeOf((*MockRepository)(nil).WriteMessage), arg0, arg1)
}

// WriteMessageWithExpectedPosition mocks base method
func (m *MockRepository) WriteMessageWithExpectedPosition(arg0 context.Context, arg1 *message.MessageEnvelope, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteMessageWithExpectedPosition", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteMessageWithExpectedPosition indicates an expected call of WriteMessageWithExpectedPosition
func (mr *MockRepositoryMockRecorder) WriteMessageWithExpectedPosition(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteMessageWithExpectedPosition", reflect.TypeOf((*MockRepository)(nil).WriteMessageWithExpectedPosition), arg0, arg1, arg2)
}
